[package]
name = "install-grub"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.3"
eyre = "0.6.12"
indoc = "2.0.5"
nix = { version = "0.29.0", features = ["fs"] }
roxmltree = "0.20.0"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
tempfile = "3.10.1"
time = "0.3.36"
walkdir = "2.5.0"
